from collections.abc import Awaitable, Callable
from typing import Protocol

from app.domain.entities import AuthType, Macro, MonitorSnapshot, SavedServer, ServerGroup, SessionHistoryEntry

OutputCallback = Callable[[str], Awaitable[None]]


class SessionHistoryRepository(Protocol):
    async def save_session(
        self,
        user_id: int,
        host: str,
        port: int,
        username: str,
        session_name: str,
        auth_type: AuthType,
        encrypted_password: str,
        encrypted_key: str,
    ) -> str: ...

    async def deactivate_sessions(self, user_id: int, session_name: str | None = None) -> None: ...

    async def get_recent_sessions(self, user_id: int, limit: int = 10) -> list[SessionHistoryEntry]: ...

    async def get_active_session(self, user_id: int, session_name: str | None = None) -> SessionHistoryEntry | None: ...


class SavedServerRepository(Protocol):
    async def upsert_server(self, server: SavedServer) -> None: ...

    async def get_server(self, user_id: int, name: str) -> SavedServer | None: ...

    async def list_servers(self, user_id: int) -> list[SavedServer]: ...

    async def delete_server(self, user_id: int, name: str) -> bool: ...

    async def update_server_group(self, user_id: int, server_name: str, group: str) -> bool: ...

    async def list_servers_by_group(self, user_id: int, group: str) -> list[SavedServer]: ...


class MacroRepository(Protocol):
    async def upsert_macro(self, macro: Macro) -> None: ...

    async def get_macro(self, user_id: int, name: str) -> Macro | None: ...

    async def list_macros(self, user_id: int) -> list[Macro]: ...

    async def delete_macro(self, user_id: int, name: str) -> bool: ...


class GroupRepository(Protocol):
    async def upsert_group(self, group: ServerGroup) -> None: ...

    async def list_groups(self, user_id: int) -> list[ServerGroup]: ...

    async def delete_group(self, user_id: int, name: str) -> bool: ...


class SecretCipher(Protocol):
    def encrypt(self, value: str) -> str: ...

    def decrypt(self, value: str) -> str: ...


class SSHRuntimeSession(Protocol):
    name: str
    user_id: int
    host: str
    port: int
    username: str
    auth_type: AuthType
    is_interactive: bool

    async def connect(
        self,
        host: str,
        port: int,
        username: str,
        password: str | None = None,
        key_data: bytes | None = None,
        default_cwd: str | None = None,
    ) -> None: ...

    async def execute(self, command: str, on_output_chunk: OutputCallback) -> int: ...

    async def open_shell(self, on_output_chunk: OutputCallback) -> None: ...

    async def send_to_shell(self, text: str) -> None: ...

    async def get_shell_cwd(self) -> str: ...

    async def close_shell(self) -> None: ...

    async def sftp_download(self, remote_path: str, local_path: str) -> None: ...

    async def sftp_upload(self, local_path: str, remote_path: str) -> None: ...

    async def disconnect(self) -> None: ...

    @property
    def is_connected(self) -> bool: ...

    @property
    def last_activity(self) -> float: ...


class SessionRegistry(Protocol):
    def create_session(self, user_id: int, name: str) -> SSHRuntimeSession: ...

    def store(self, user_id: int, session: SSHRuntimeSession) -> None: ...

    def get(self, user_id: int, name: str | None = None) -> SSHRuntimeSession | None: ...

    def get_active(self, user_id: int) -> SSHRuntimeSession | None: ...

    def get_active_name(self, user_id: int) -> str | None: ...

    def get_all(self, user_id: int) -> dict[str, SSHRuntimeSession]: ...

    def switch(self, user_id: int, name: str) -> SSHRuntimeSession | None: ...

    async def remove(self, user_id: int, name: str | None = None) -> None: ...

    async def remove_all(self, user_id: int) -> None: ...

    async def close_all(self) -> None: ...

    def check_timeouts(self, timeout_minutes: int) -> list[tuple[int, str]]: ...


class StreamPublisher(Protocol):
    def generate_stream_id(self) -> int: ...

    async def publish(self, chat_id: int, stream_id: int, text: str, parse_mode: str = "HTML") -> bool: ...


class MonitorCollector(Protocol):
    async def collect(self, session: SSHRuntimeSession) -> MonitorSnapshot: ...
